name: "CreeperRecover"
version: "1.1.0-mc1.19.4"
folia-supported: true
main: "de.rafael.plugins.creeper.recover.CreeperRecover"
api-version: "1.19"
description: "Recovers all destroyed blocks by Creeper or other Entities"
author: "HttpRafa"
